homeapp/urls.py
from django.urls import path
from . import views

app_name = "homeapp"

urlpatterns = [
    path('', views.home, name='home'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name="contact"),
    path('complain_form', views.complain_form, name="complain_form"),
    #path('complain/success', views.complain_success, name="complain_success"),
    #path('profile', views.profile, name='profile'),
    #path('term', views.term, name='term'),
    #path('signin_success', views.signin_success, name='signin_success'),
    path('error', views.error, name='error'),
]

oml/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from homeapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homeapp.urls')),
    path('study/', include('study.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

study/urls.py
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "study"

urlpatterns = [
    path('course/home', views.course_home, name='course_home'),
    #path('course/select_class', views.course_select_class, name='course_select_class'),
    #path('course/select_custom', views.course_select_custom, name='course_select_custom'),
    path('course/instruction', views.course_instruction, name='course_instruction'),
    #path('course/warn', views.course_warn, name='course_warn'),
    #path('course/continue', views.course_home, name='course_continue'),
    #path('course/sheet', views.course_sheet, name='course_sheet'),
    path('course/study', views.course_study, name='course_study'),
    path('course/summary', views.course_summary, name='course_summary'),
    #path('course/certificate', views.course_certificate, name='course_certificate'),
    #path('problem/select', views.problem_select, name='problem_select'),
    #path('problem/do', views.problem_do, name='problem_do'),

    path('problem/demo/pre/instruction', views.problem_demo_pre1, name='problem_demo_pre1'),
    path('problem/demo/pre/choice', views.problem_demo_pre2, name='problem_demo_pre2'),
    path('problem/demo/pre/choice/correct', views.correct_pre2, name='correct_pre2'),
    path('problem/demo/pre/choice/wrong', views.wrong_pre2, name='wrong_pre2'),
    path('problem/demo/pre/fillin', views.problem_demo_pre3, name='problem_demo_pre3'),

    path('problem/demo/post/instruction', views.problem_demo_post1, name='problem_demo_post1'),
    path('problem/demo/post/choice', views.problem_demo_post2, name='problem_demo_post2'),
    path('problem/demo/post/choice/correct', views.correct_post2, name='correct_post2'),
    path('problem/demo/post/choice/wrong', views.wrong_post2, name='wrong_post2'),
    path('problem/demo/post/fillin', views.problem_demo_post3, name='problem_demo_post3'),

    path('download/<str:oml_sheet>', views.download_file, name='download_file'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

homeapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator


# Create your models here.\
'''
class UserOptimal(models.Model):
     username = models.ForeignKey(User, on_delete=models.CASCADE)
     user_email = models.EmailField
     user_type = models.SmallIntegerField
     user_school = models.CharField
     user_contact = models.CharField
     user_regdate = models.DateField

class UserStudent(models.Model):
     username = models.ForeignKey(User, on_delete=models.CASCADE)
     user_type = models.ForeignKey(UserOptimum, on_delete=models.CASCADE)
     student_grade = models.SmallIntegerField # Matthayom 1, 2, 3
     student_class = models.PositiveSmallIntegerField(validators=[MinValueValidator(1), MaxValueValidator(99)])
'''

homeapp/views.py
from django.shortcuts import render
import datetime

# Create your views here.
def home(request):
    #print()
    #message="id:%s, uasername:%s firstname:%s, lastname:%s"%(request.user.pk, request.user.username, request.user.first_name, request.user.last_name)
    #now = datetime.datetime.now()
    return render(request, 'homeapp/home.html')

def about(request):
    return render(request, 'homeapp/about.html')

def contact(request):
    return render(request, 'homeapp/contact.html')

def complain_form(request):
    return render(request, 'homeapp/complain_form.html')

def complain_success(request):
    return render(request, 'homeapp/complain_success.html')

#from account
def profile(request):
    return render(request, 'homeapp/profile.html')

def term(request):
    return render(request, 'homeapp/term.html')

def register_student(request):
    return render(request, 'homeapp/register_student.html')

def register_teacher(request):
    return render(request, 'homeapp/register_teacher.html')

def register_success(request):
    return render(request, 'homeapp/register_success.html')

def signin_form(request):
    return render(request, 'homeapp/signin_form.html')

def signin_success(request):
    return render(request, 'homeapp/signin_success.html')

def error(request):
    return render(request, 'homeapp/error.html')

homeapp/templates/homeapp/about.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OML | About</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
     <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Prompt">
    <style>
      body {
        font-family: 'Prompt', sans-serif;
        font-size: 22px;
      }
    </style>
</head>

<body style="background:#364966">
    <div style="background:#435D74" class="text-white">
<br>
<h1>เกี่ยวกับเรา</h1>
<br> 
<h5>ซอฟต์แวร์นี้เป็นผลงานที่พัฒนาขึ้นโดยนายณรบดี โรจนานันท์, นายภูริณัฐ พลอาสา และนายศุภวิชญ์ กาสา
จากโรงเรียนสวนกุหลาบวิทยาลัย รังสิต (โครงการ วมว.มธ.-สกร.) 
<br>ภายใต้การดูแลของครูณัฐพล บัวอุไร, ครูลัดดาวัลย์ เอี่ยมสมบูรณ์ และ ผศ.ดร. วสิศ ลิ้มประเสริฐ 
ภายใต้โครงการแข่งขันพัฒนาโปรแกรมคอมพิวเตอร์ประเทศไทย ครั้งที่ 24 <br>ซึ่งสนับสนุนโดย 
สำนักงานพัฒนาวิทยาศาสตร์และเทคโนโลยีแห่งชาติ <br>โดยมีวัตถุประสงค์เพื่อส่งเสริมให้นักเรียนและนักศึกษา
ได้เรียนรู้และฝึกทักษะในการพัฒนาซอฟต์แวร์ ลิขสิทธิ์ของซอฟต์แวร์นี้จึงเป็นของผู้พัฒนา 
ซึ่งผู้พัฒนาได้อนุญาตให้<br>สำนักงานพัฒนาวิทยาศาสตร์และเทคโนโลยีแห่งชาติ เผยแพร่ซอฟต์แวร์นี้
ตาม “ต้นฉบับ” โดยไม่มีการแก้ไขดัดแปลงใดๆ ทั้งสิ้น 
ให้แก่บุคคลทั่วไปได้ใช้เพื่อประโยชน์ส่วนบุคคลหรือประโยชน์ทางการศึกษาที่ไม่มีวัตถุประสงค์ในเชิงพาณิชย์ 
โดยไม่คิดค่าตอบแทนการใช้ซอฟต์แวร์ <br>ดังนั้น สำนักงานพัฒนาวิทยาศาสตร์และเทคโนโลยีแห่งชาติ 
จึงไม่มีหน้าที่ในการดูแล บำรุงรักษา จัดการอบรมการใช้งาน หรือพัฒนาประสิทธิภาพซอฟต์แวร์ 
รวมทั้งไม่รับรองความถูกต้องหรือประสิทธิภาพการทำงานของซอฟต์แวร์ ตลอดจนไม่รับประกันความเสียหายต่างๆ อันเกิดจากการใช้ซอฟต์แวร์นี้ทั้งสิ้น</h5>
<br>
    <center><a href ={% url "homeapp:home" %}><button type="button" class="btn btn-danger btn-lg">กลับหน้าหลัก</button></a></center><br>
    </div>
<footer>
    <span><h3><font color="white">Optimal</font><font color="red">Learning</font></h3></span>
    <span><font color="white"><h6>© 2022 OML Team</h6></font></span>
</footer>


</body>
</html>

homeapp/templates/homeapp/complain_form.html
<!DOCTYPE html>
<html>
  <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Complain_form</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Prompt">
    <style>
      body {
        font-family: 'Prompt', sans-serif;
        font-size: 22px;
      }
    </style>

    {% if user.is_superuser %}

<body style="background:#364966">
<div style="background:#435D74" class="text-white">
<center><h1>Complain Forms</h1></center>

<form action="/action_page.php">
  <div class="mb-3 row">
    <center><label for="fname" class="col-sm-2 col-form-label"><h5>ชื่อผู้แจ้ง</h5></label>
      <div class="col-sm-10">
       <input type="text" class="form-control-sm" id="fname">
      </div>
<br>    
    <center><label for="iname" class="col-sm-2 col-form-label"><h5>ปัญหาที่</h5></label>
      <div class="col-sm-10">
         <input type="text" class="form-control-sm" id="iname">
      </div>      
<br>
    <center><label for="jname" class="col-sm-2 col-form-label"><h5>รหัสของข้อมูลที่เกี่ยวข้อง</h5></label>
      <div class="col-sm-10">
        <input type="text" class="form-control-sm" id="jname">
      </div>  
<br>
    <center><label for="kname" class="col-sm-2 col-form-label"><h5>ลักษณะของปัญหา</h5></label>
      <div class="col-sm-10">
        <input type="text" class="form-control-sm" id="kname">
      </div>
<br>
    <center><label for="lname" class="col-sm-2 col-form-label"><h5>คำอธิบายเพิ่มเติม</h5></label>
      <div class="col-sm-10">
       <input type="text" class="form-control-sm" id="lname">
      </div>
  </div>  
<br>  
  <center><button type="button" class="btn btn-danger btn-lg">Submit</button></center>  
</form> 
<br>
<center><a href ={% url "homeapp:home" %}><button type="button" class="btn btn-danger btn-lg">back to homepage</button></a>
</center>
</div>

<footer>
    <span><h3><font color="white">Optimal</font><font color="red">Learning</font></h3></span>
    <span><font color="white"><h6>© 2022 OML Team</h6></font></span>
</footer>


</body>
</html>
{% else %}
{% endif %}

homeapp/templates/homeapp/complain_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Complain_success</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Prompt">
    <style>
      body {
        font-family: 'Prompt', sans-serif;
        font-size: 22px;
      }
    </style>
</head>
<body style="background:#364966">
    <div style="background:#435D74" class="text-white">
<br><br>    
    <center><h1>เราได้รับคำร้องเรียนของคุณเเล้ว</h1></center>
<br><br>
<center><svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="currentColor" class="bi bi-check-circle" viewBox="0 0 16 16">
    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
    <path d="M10.97 4.97a.235.235 0 0 0-.02.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05z"/>
  </svg></center>    
<br><br>
<center>
<a href ={% url "homeapp:home" %}><button type="button" class="btn btn-danger btn-lg">back to homepage</button></a>
</center>
    </div>
<br><br>
<footer>
    <span><h3><font color="white">Optimal</font><font color="red">Learning</font></h3></span>
    <span><font color="white"><h6>© 2022 OML Team</h6></font></span>
</footer>

</body>
</html>

homeapp/templates/homeapp/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OML | Contact</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Prompt">
    <style>
      body {
        font-family: 'Prompt', sans-serif;
        font-size: 22px;
      }
    </style>
</head>
<body style="background:#364966">
    <div style="background:#435D74" class="text-white">
   <br><center><h1>ติดต่อ</h1>
        <br>ผู้จัดทำเว็บไซต์ martnarabodee@gmail.com
        <br><br><a href ={% url "homeapp:home" %}><button type="button" class="btn btn-danger btn-lg">กลับหน้าหลัก</button></a></center><br>
    </div>
<footer>
    <span><h3><font color="white">Optimal</font><font color="red">Learning</font></h3></span>
    <span><font color="white"><h6>© 2022 OML Team</h6></font></span>
</footer>

</body>
</html>

homeapp/templates/homeapp/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Prompt">
    <style>
      body {
        font-family: 'Prompt', sans-serif;
        font-size: 36px;
      }
    </style>
</head>
<body style="background:#364966" class="text-center">
   <div style="background:#435D74" class="text-white">
   <br>Error: Page not avalible<br>
   หน้าดังกล่าวไม่พร้อมใช้งานในขณะนี้<br></br>
       <center><a href ="{% url "homeapp:home" %}"><button type="button" class="btn btn-danger btn-lg">กลับหน้าหลัก</button></a>
       </center</font></center><br>
   </div>
   <div align="left">
       <footer>
    <span><h3><font color="white">Optimal</font><font color="red">Learning</font></h3></span>
    <span><font color="white"><h6>© 2022 OML Team</h6></font></span>
</footer>
   </div>
   </body>
</html>

homeapp/templates/homeapp/home.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OML</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Prompt">
    <style>
      body {
        font-family: 'Prompt', sans-serif;
        font-size: 22px;
      }
    </style>
</head>
<body style="background:#435D74" class="text-white">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-2">
        <div align="left">
            {% load static %}
            &nbsp<img src="{% static "homeapp/logo.png" %}" width="20%" height="20%">
        </div>
        <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
          <br><a href="{% url "study:course_home" %}" class="nav-link px-2 link-white"><font color="white"><h5>คอร์ส</h5></font></a>
          <a href="{% url "homeapp:error" %}" class="nav-link px-2 link-white"><font color="white"><h5>โจทย์</h5></font></a>
          <a href="{% url "homeapp:about" %}" class="nav-link px-2 link-white"><font color="white"><h5>เกี่ยวกับ</h5></font></a>
    <!--      <a href="{% url "homeapp:complain_form" %}" class="nav-link px-2 link-white"><font color="white"><h5>แจ้งปัญหา</h5></font></a> -->
            &nbsp;<a href="{% url "homeapp:contact" %}" class="nav-link px-2 link-white"><font color="white"><h5>ติดต่อ</h5></font></a>
            <a href="{% url "homeapp:error" %}"><button type="button" class="btn btn-danger">เข้าสู่ระบบ</button></a>
            &nbsp;<a href = "{% url "homeapp:error" %}"><button type="button" class="btn btn-danger">ลงทะเบียน</button></a>
        </ul>
      </header>
<div style="background:#364966">
    <br><center><h1>แหล่งเรียนรู้คณิตศาสตร์เพื่อนักเรียน</h1></center>
    <br><center><h1>เรียนได้ตามรูปแบบการเรียนรู้ของตนเอง</h1></center>
    <br><br><center><h2>ออกแบบรูปแบบการเรียนรู้โดย AI</h2></center>
    <br><center><h2>พัฒนาโดยรุ่นพี่ที่มากประสบการณ์</h2></center>
    <br><center><h2>เข้าใช้ระบบได้เลย ฟรี!</h2></center>
    <br><br><center><a href = "{% url "study:course_home" %}"><button type="button" class="btn btn-danger btn-lg"><h1>เริ่มเรียนเลย</h1></button><a></a></center>
   <br><br>
</div>
    <footer>
    <span><h3><font color="white">Optimal</font><font color="red">Learning</font></h3></span>
    <span><font color="white"><h6>© 2022 OML Team</h6></font></span>
    </footer>

</body>
</html>

homeapp/templates/homeapp/register_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register sucess</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Prompt">
    <style>
      body {
        font-family: 'Prompt', sans-serif;
        font-size: 22px;
      }
    </style>
</head>
<body style="background:#364966">
<div style="background:#435D74" class="text-white">
    <center><h1>Finished</h1>
    <br><br><br><h3>"ลงทะเบียนสำเร็จแล้ว"</h3>
    <br><br>
    <svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" fill="currentColor" class="bi bi-check-circle-fill" viewBox="0 0 16 16">
        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
      </svg>
<br><br><br><br><a href ="{% url "homeapp:home" %}"><button type="button" class="btn btn-danger btn-lg">Back to homepage</button></a>
    </center>
</div>
<br><br>
<footer>
    <span><h3><font color="white">Optimal</font><font color="red">Learning</font></h3></span>
    <span><font color="white"><h6>© 2022 OML Team</h6></font></span>
</footer>

</body>
</html>

homeapp/templates/homeapp/register_teacher.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"> 
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register_teacher</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Prompt">
    <style>
      body {
        font-family: 'Prompt', sans-serif;
        font-size: 22px;
      }
    </style>
</head>
<body style="background:#364966">
 <div style="background:#435D74" class="text-white">
<form action="/action_page.php">
  <center><h2>Register for teacher</h2></center><br><br>
  <div class="mb-3 row">
      <center><label for="fname" class="col-sm-2 col-form-label"><h3>ชื่อผู้ใช้</h3></label>

      <div class="col-sm-10">
        <input type="text" class="form-control-sm" id="fname">
      </div>
<br>  
      <center><label for="iname" class="col-sm-2 col-form-label"><h3>รหัสผ่าน</h3></label>
     <div class="col-sm-10">
        <input type="number" class="form-control-sm" id="iname">
     </div>
<br>
          <center><label for="jname" class="col-sm-2 col-form-label"><h3>ชื่อ-นามสกุล</h3></label>
     <div class="col-sm-10">
       <input type="text" class="form-control-sm" id="jname">
     </div>
<br>
              <center><label for="kname" class="col-sm-2 col-form-label"><h3>E-mail</h3></label>
      <div class="col-sm-10">
        <input type="text" class="form-control-sm" id="kname">
      </div>
<br>
                  <center><label for="lname" class="col-sm-2 col-form-label"><h3>โรงเรียน</h3></label>
       <div class="col-sm-10">
         <input type="text" class="form-control-sm" id="lname">
       </div>
<br>
                      <center><label for="mname" class="col-sm-2 col-form-label"><h3>ระดับชั้นที่สอน</h3></label>
       <div class="col-sm-10">
          <input type="text" class="form-control-sm" id="mname">
        </div>
<br>
                          <center><label for="nname" class="col-sm-2 col-form-label"><h3>ข้อมูลติดต่อเพิ่มเติม</h3></label>
       <div class="col-sm-10">
         <input type="text" class="form-control-sm" id="nname">
       </div>

<br>
                              <button type="button" class="btn btn-danger"><h3>Submit</h3></button>
</form> 
<br><br>

     <a href ="{% url "homeapp:home" %}"><button type="button" class="btn btn-danger"><h3>back to homepage</h3></button></a>
</div>
</div>
<br><br>
<footer>
    <span><h3><font color="white">Optimal</font><font color="red">Learning</font></h3></span>
    <span><font color="white"><h6>© 2022 OML Team</h6></font></span>
</footer>


</body>
</html>

homeapp/templates/homeapp/signin_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>sign in_success</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Prompt">
    <style>
      body {
        font-family: 'Prompt', sans-serif;
        font-size: 22px;
      }
    </style>
</head>
<body style="background:#364966">
    <div style="background:#435D74" class="text-white">
<br>    
    <center><h1>เข้าสู่ระบบสำเร็จ</h1>
<br><br><br>        
    <a href ="{% url "homeapp:home" %}"><button type="button" class="btn btn-danger btn-lg">go back</button></a>
<br><br><br>    
    <a href ="{% url "homeapp:homeapp" %}"><button type="button" class="btn btn-danger btn-lg">your homeapp</button></a>  
<br><br><br>    
    <a href ="{% url "homeapp:home" %}"><button type="button" class="btn btn-danger btn-lg">back to homepage</button></a> 
    </center>
    </div>
<br><br>
<footer>
    <span><h3><font color="white">Optimal</font><font color="red">Learning</font></h3></span>
    <span><font color="white"><h6>© 2022 OML Team</h6></font></span>
</footer>

</body>
</html>