homeapp/urls.py
from django.urls import path
from . import views

app_name = "homeapp"

urlpatterns = [
    path('', views.home, name='home'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name="contact"),
    path('complain_form', views.complain_form, name="complain_form"),
    #path('complain/success', views.complain_success, name="complain_success"),
    #path('profile', views.profile, name='profile'),
    #path('term', views.term, name='term'),
    #path('signin_success', views.signin_success, name='signin_success'),
    path('error', views.error, name='error'),
]

oml/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from homeapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homeapp.urls')),
    path('study/', include('study.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

study/urls.py
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "study"

urlpatterns = [
    path('course/home', views.course_home, name='course_home'),
    #path('course/select_class', views.course_select_class, name='course_select_class'),
    #path('course/select_custom', views.course_select_custom, name='course_select_custom'),
    path('course/instruction', views.course_instruction, name='course_instruction'),
    #path('course/warn', views.course_warn, name='course_warn'),
    #path('course/continue', views.course_home, name='course_continue'),
    #path('course/sheet', views.course_sheet, name='course_sheet'),
    path('course/study', views.course_study, name='course_study'),
    path('course/summary', views.course_summary, name='course_summary'),
    #path('course/certificate', views.course_certificate, name='course_certificate'),
    #path('problem/select', views.problem_select, name='problem_select'),
    #path('problem/do', views.problem_do, name='problem_do'),

    path('problem/demo/pre/instruction', views.problem_demo_pre1, name='problem_demo_pre1'),
    path('problem/demo/pre/choice', views.problem_demo_pre2, name='problem_demo_pre2'),
    path('problem/demo/pre/choice/correct', views.correct_pre2, name='correct_pre2'),
    path('problem/demo/pre/choice/wrong', views.wrong_pre2, name='wrong_pre2'),
    path('problem/demo/pre/fillin', views.problem_demo_pre3, name='problem_demo_pre3'),

    path('problem/demo/post/instruction', views.problem_demo_post1, name='problem_demo_post1'),
    path('problem/demo/post/choice', views.problem_demo_post2, name='problem_demo_post2'),
    path('problem/demo/post/choice/correct', views.correct_post2, name='correct_post2'),
    path('problem/demo/post/choice/wrong', views.wrong_post2, name='wrong_post2'),
    path('problem/demo/post/fillin', views.problem_demo_post3, name='problem_demo_post3'),

    path('download/<str:oml_sheet>', views.download_file, name='download_file'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

study/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE
from django.db.models.fields import IntegerField, URLField

# Create your models here.
class CourseInfo(models.Model):
    course_id  = models.PositiveIntegerField(primary_key=True, default=1)
    course_name = models.CharField(max_length=100)
    course_description = models.CharField
    is_use = models.BooleanField(default=True)

    def __str__(self):
        return self.caption

'''
class CourseVideo (models.Model):
    cv_id = models.PositiveIntegerField #course video id
    cv_lecturer = models.CharField 
    cv_video = URLField
    is_use = models.BooleanField(default=True)

    def __str__(self) -> str:
        return self.cv_id


class CourseMaterial (models.Model):
    course_id = models.ForeignKey(CourseInfo, on_delete=models.CASCADE)
    cv_id = models.ForeignKey(CourseVideo, on_delete=models.CASCADE) 
    cm_worksheet = models.FileField     #store course's worksheet
    is_use = models.BooleanField(default=True)

    def __str__(self) -> str:
        return self.course_id


class RegisterCourse (models.Model):
    #user = models.OneToOneField(User, on_delete=models.CASCADE)
    course_id = models.ForeignKey(CourseInfo, on_delete=models.CASCADE)
    RegisterCourseTime = models.DateTimeField


# Problem Classes
class ProblemInfoDeep (models.Model):
    pb_id = models.IntegerField(primary_key=True)
    pb_material = models.JSONField
    pb_hard = models.SmallIntegerField
    pb_error = models.JSONField
    pb_size = models.SmallIntegerField
    pb_source = models.CharField

""""
class ProblemKeyInteger (models.Model):
    pb_id = models.ManyToManyField(ProblemInfoDeep, primary_key=True)
    pb_key = models.IntegerField

class ProblemKeyChar (models.Model):
    pb_id = models.ManyToManyField(ProblemInfoDeep, primary_key=True)
    pb_key = models.CharField

class ProblemKeyPicture (models.Model):
    pb_id = models.ManyToManyField(ProblemInfoDeep, primary_key=True)
    pb_id = models.ImageField

class ProblemInfoShow (models.Model):
    pb_id = models.ManyToManyField(ProblemInfoDeep, primary_key=True)
    pb_key = models.ForeignKey(ProblemInfoDeep, on_delete=models.CASCADE)
    pb_image = models.ImageField
    pb_status = models.SmallIntegerField
    pb_donescore = models.SmallIntegerField
    pb_type = models.SmallIntegerField
"""'''

class VideoDemo(models.Model):
    caption = models.CharField(max_length=100)
    video = models.FileField(upload_to="video/%y")
    def __str__(self):
        return self.caption

study/views.py
from django.shortcuts import render
from .models import VideoDemo
# Import mimetypes module
import mimetypes
# import os module
import os
# Import HttpResponse module
from django.http.response import HttpResponse

# Create your views here.
def course_home(request):
    return render(request, 'study/course_home.html')

def course_select_class(request):
    return render(request, 'study/course_select_class.html')

def course_select_custom(request):
    return render(request, 'study/course_select_custom.html')

def course_instruction(request):
    return render(request, 'study/course_instruction.html')

# Define function to download pdf file using template
def download_file(request, filename=''):
    if filename != '':
        # Define Django project base directory
        BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        # Define the full file path
        filepath = BASE_DIR + '/study/static/study/sheet/' + filename
        # Open the file for reading content
        path = open(filepath, 'rb')
        # Set the mime type
        mime_type, _ = mimetypes.guess_type(filepath)
        # Set the return value of the HttpResponse
        response = HttpResponse(pdf)
        response['Content-Type'] = 'application/pdf'
        response['Content-disposition'] = 'attachment ; filename = {}'.format(oml_sheet)
        # Return the response value
        return response
    else:
        # Load the template
        return render(request, 'study/course_instruction.html')


def course_warn(request):
    return render(request, 'study/course_warn.html')

def course_continue(request):
    return render(request, 'study/course_continue.html')

def course_sheet(request):
    return render(request, 'study/course_sheet.html')

def course_study(request):
    video = VideoDemo.objects.all()
    return render(request,"study/course_study.html",{"video":video})

def course_summary(request):
    return render(request, 'study/course_summary.html')

def course_certificate(request):
    return render(request, 'study/course_certificate.html')

def problem_select(request):
    return render(request, 'study/problem_select.html')

def problem_do(request):
    return render(request, 'study/problem_do.html')

def problem_demo_pre1(request):
    return render(request, 'study/problem_demo_pre1.html')

def problem_demo_pre2(request):
    return render(request, 'study/problem_demo_pre2.html')

def problem_demo_pre3(request):
    return render(request, 'study/problem_demo_pre3.html')

def problem_demo_post1(request):
    return render(request, 'study/problem_demo_post1.html')

def problem_demo_post2(request):
    return render(request, 'study/problem_demo_post2.html')

def problem_demo_post3(request):
    return render(request, 'study/problem_demo_post3.html')

def correct_pre2(request):
    return render(request, 'study/correct_pre2.html')

def correct_post2(request):
    return render(request, 'study/correct_post2.html')

def wrong_pre2(request):
    return render(request, 'study/wrong_pre2.html')

def wrong_post2(request):
    return render(request, 'study/wrong_post2.html')

study/templates/study/course_home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OML | Course</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Prompt">
    <style>
      body {
        font-family: 'Prompt', serif;
        font-size: 22px;
      }
    </style>
</head>
<body style="background:#364966">
    <div style="background:#435D74" class="text-white">
        <br>
    <center><h1>เลือกแนวทางการเรียน</h1></center><br>
    <center><a href ={% url "study:problem_demo_pre1" %} target = ><button type="button" class="btn btn-danger btn-lg">เรียนตามระดับชั้น</button></a></center>  <br>
    <center><a href ={% url "homeapp:error" %}><button type="button" class="btn btn-danger btn-lg">เรียนตามความต้องการ</button></a></center>  <br>
    <center><a href ={% url "homeapp:home" %} target = ><button type="button" style="background:#7B7B7B" class="btn btn-lg text-white">กลับสู่หน้าหลัก</button></a></center>
        <br>
    </div>
<footer>
    <span><h3><font color="white">Optimal</font><font color="red">Learning</font></span>
    <span><font color="white"><h6>© 2022 OML Team</h6></font></span>
</footer>

</body>
</html>

study/templates/study/course_select_class.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Course select class</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Prompt">
    <style>
      body {
        font-family: 'Prompt', serif;
        font-size: 22px;
      }
    </style>
</head>
<body style="background:#364966">
    <div style="background:#435D74" class="text-white">
    <center><h1>เรียนตามระดับชั้นเรียน</h1></center> <br><br>
    </div>
    <div style="background:#435D74" class="text-white">
    <center><a href ={% url "study:course_instruction" %}><button type="button" class="btn btn-danger btn-lg"> ระดับชั้นมัธยมศักษาปีที่ 1 </button></a></center>  <br>
    <center><a href ={% url "study:course_instruction" %}><button type="button" class="btn btn-danger btn-lg"> ระดับชั้นมัธยมศักษาปีที่ 2 </button></a></center>  <br>
    <center><a href ={% url "study:course_instruction" %}><button type="button" class="btn btn-danger btn-lg"> ระดับชั้นมัธยมศักษาปีที่ 3 </button></a></center>  <br>
    <center><h2>กลับสู่หน้าหลัก</h2></center> <br>
    <center><a href ={% url "homeapp:home" %} target = ><button type="button" class="btn btn-danger btn-lg"> back to homepage </button></a></center> 
    </div>
<br><br>
<footer>
    <span><h3><font color="white">Optimal</font><font color="red">Learning</font><font color="white"> V. a1.0</font></h3></span>
    <span><font color="white"><h6>© 2022 OML Team</h6></font></span>
</footer>

</body>
</html>

study/templates/study/course_select_custom.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Course select custom</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Prompt">
    <style>
      body {
        font-family: 'Prompt', serif;
        font-size: 22px;
      }
    </style>
</head>
<body style="background:#364966">
    <div style="background:#435D74" class="text-white">
    <center><h1>เรียนตามใจ</h1></center> <br>
    </div>    
    <div style="background:#435D74" class="text-white">
    <center><a href ={% url "study:course_instruction" %} target = ><button type="button" class="btn btn-danger btn-lg">เนื้อหาเรื่องที่ 1 </button></a></center>  <br>
    <center><a href ={% url "study:course_instruction" %} target = ><button type="button" class="btn btn-danger btn-lg"> เนื้อหาเรื่องที่ 2 </button></a></center>  <br>
    <center><a href ={% url "study:course_warn" %} target = ><button type="button" class="btn btn-danger btn-lg"> เนื้อหาเรื่องที่ 3 </button></a></center>  <br>
        <center><h2>กลับสู่หน้าหลัก</h2></center> <br>
        <center><a href ={% url "homeapp:home" %} target = ><button type="button" class="btn btn-danger btn-lg"> back to homepage </button></a></center> 
    </div>
<br><br>
<footer>
    <span><h3><font color="white">Optimal</font><font color="red">Learning</font><font color="white"> V. a1.0</font></h3></span>
    <span><font color="white"><h6>© 2022 OML Team</h6></font></span>
</footer>

</body>
</html>

study/templates/study/problem_demo_post2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OML | ทดสอบหลังเรียน</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Prompt">
    <style>
      body {
        font-family: 'Prompt', serif;
        font-size: 22px;
      }
    </style>
</head>
<body style="background:#364966">
    <div style="background:#364966" class="text-white">
    <center><h1>ทดสอบหลังเรียน M132005</h1></center>
        <center><h2>เรื่อง อัตราส่วนตรีโกณมิติ ม.3</h2></center>

        <center><h5>ชื่อผู้ใช้ นายมาลี เจริญยิ่ง &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;รหัสข้อ 9D2ACD</h5></center><br>
        <center>
            {% load static %}
            <img src="{% static "study/demo/trigon_post.png" %}">
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <img src="{% static "study/demo/trigon_pre2.png" %}" width="25%" height="25%">
        </center>
    <br>
        <center>
    <div class="container">
        <div class="row">
            <div class="col"></div>
            <div class="col">
                <a href="{% url "study:wrong_post2" %}"><button type="button" class="btn btn-light btn-lg">(1)</button></a>
            </div>
            <div class="col">
                <a href="{% url "study:wrong_post2" %}"><button type="button" class="btn btn-light btn-lg">(2)</button></a>
            </div>
            <div class="col">
                <a href="{% url "study:wrong_post2" %}"><button type="button" class="btn btn-light btn-lg">(3)</button></a>
            </div>
            <div class="col">
                <a href="{% url "study:correct_post2" %}"><button type="button" class="btn btn-light btn-lg">(4)</button></a>
            </div>
            <div class="col"></div>
        <br>
        </div>
    </div>
        </center><br>

        <div style="background:#435D74" class="text-white">
            <br>
         <center>
    <div class="container">
        <div class="row">
            <div class="col"></div>
            <div class="col">
             	<button type="button" class="btn btn-lg text-white" style="background:#7B7B7B">แจ้งปัญหา</button>
            </div>
            <div class="col">
                <a href ={% url "study:problem_demo_post2" %}><button type="button" class="btn btn-danger btn-lg">ย้อนกลับ</button></a>
            </div>
            <div class="col">
                <a href ={% url "study:problem_demo_post3" %}><button type="button" class="btn btn-danger btn-lg">ถัดไป</button></a>
            </div>
            <div class="col">
             <a href ={% url "study:course_summary" %} ><button type="button" class="btn btn-lg text-white" style="background:#7B7B7B">ส่งแบบทดสอบ</button></a>
            </div>
            <div class="col"></div>
        <br>
        </div>
    </div>
         </center>
            <br>
        </div>
    </div>
<footer>
    <span><h3><font color="white">Optimal</font><font color="red">Learning</font></span>
    <span><font color="white"><h6>© 2022 OML Team</h6></font></span>
</footer>
</body>
</html>

study/templates/study/problem_demo_pre2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OML | ทดสอบก่อนเรียน</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Prompt">
    <style>
      body {
        font-family: 'Prompt', serif;
        font-size: 22px;
      }
    </style>
</head>
<body style="background:#364966">
    <div style="background:#364966" class="text-white">
    <center><h1>ทดสอบก่อนเรียน M132005</h1></center>
        <center><h2>เรื่อง อัตราส่วนตรีโกณมิติ ม.3</h2></center>

        <center><h5>ชื่อผู้ใช้ นายมาลี เจริญยิ่ง &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;รหัสข้อ 9D2ACD</h5></center><br>
        <center>
            {% load static %}
            <img src="{% static "study/demo/trigon_pre1.png" %}">
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <img src="{% static "study/demo/trigon_pre2.png" %}" width="25%" height="25%">
        </center>
    <br>
        <center>
    <div class="container">
        <div class="row">
            <div class="col"></div>
            <div class="col">
                <a href="{% url "study:wrong_pre2" %}"><button type="button" class="btn btn-light btn-lg">(1)</button></a>
            </div>
            <div class="col">
                <a href="{% url "study:wrong_pre2" %}"><button type="button" class="btn btn-light btn-lg">(2)</button></a>
            </div>
            <div class="col">
                <a href="{% url "study:wrong_pre2" %}"><button type="button" class="btn btn-light btn-lg">(3)</button></a>
            </div>
            <div class="col">
                <a href="{% url "study:correct_pre2" %}"><button type="button" class="btn btn-light btn-lg">(4)</button></a>
            </div>
            <div class="col"></div>
        </div>
    </div><br>
        </center>
        <div style="background:#435D74" class="text-white">
            <br>
         <center>
    <div class="container">
        <div class="row">
            <div class="col"></div>
            <div class="col">
             	<button type="button" class="btn btn-lg text-white" style="background:#7B7B7B">แจ้งปัญหา</button>
            </div>
            <div class="col">
                <a href ={% url "study:problem_demo_pre2" %}><button type="button" class="btn btn-danger btn-lg">ย้อนกลับ</button></a>
            </div>
            <div class="col">
                <a href ={% url "study:problem_demo_pre3" %}><button type="button" class="btn btn-danger btn-lg">ถัดไป</button></a>
            </div>
            <div class="col">
             <a href ={% url "study:course_instruction" %} ><button type="button" class="btn btn-lg text-white" style="background:#7B7B7B">ส่งแบบทดสอบ</button></a>
            </div>
            <div class="col"></div>
        <br>
        </div>
    </div>         </center>
            <br>
        </div>
    </div>
<footer>
    <span><h3><font color="white">Optimal</font><font color="red">Learning</font></span>
    <span><font color="white"><h6>© 2022 OML Team</h6></font></span>
</footer>
</body>
</html>

study/templates/study/problem_demo_pre3.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OML | ทดสอบก่อนเรียน</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Prompt">
    <style>
      body {
        font-family: 'Prompt', serif;
        font-size: 22px;
      }
    </style>
</head>
<body style="background:#364966">
    <div style="background:#364966" class="text-white">
    <center><h1>ทดสอบก่อนเรียน M132005</h1></center>
        <center><h2>เรื่อง อัตราส่วนตรีโกณมิติ ม.3</h2></center>
        <center><h5>ชื่อผู้ใช้ นายมาลี เจริญยิ่ง &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;รหัสข้อ 9D2ACD</h5></center>
        <br>
        <center>
            {% load static %}
            <img src="{% static "study/demo/pb_pre3.png" %}" width="45%" height="45%">
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <img src="{% static "study/demo/trigon_pre2.png" %}" width="25%" height="25%">
        </center>
    <br>
            <center><div class="col-sm-7">
            <input type="text" class="form-control" id="inputUsername">
            </div></center><br>

        <div style="background:#435D74" class="text-white"><br>
         <center>
    <div class="container">
        <div class="row">
            <div class="col"></div>
            <div class="col">
             	<button type="button" class="btn btn-lg text-white" style="background:#7B7B7B">แจ้งปัญหา</button>
            </div>
            <div class="col">
                <a href ={% url "study:problem_demo_pre2" %}><button type="button" class="btn btn-danger btn-lg">ย้อนกลับ</button></a>
            </div>
            <div class="col">
                <a href ={% url "study:problem_demo_pre3" %}><button type="button" class="btn btn-danger btn-lg">ถัดไป</button></a>
            </div>
            <div class="col">
             <a href ={% url "study:course_instruction" %} ><button type="button" class="btn btn-lg text-white" style="background:#7B7B7B">ส่งแบบทดสอบ</button></a>

            </div>
            <div class="col"></div>
        <br>
        </div>
    </div>         </center><br>
        </div>
<footer>
    <span><h3><font color="white">Optimal</font><font color="red">Learning</font></span>
    <span><font color="white"><h6>© 2022 OML Team</h6></font></span>
</footer>
</body>
</html>